language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run lint
  - npm run build
  - npm test
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info
