version: '3.3'

services:
  db:
    container_name: makina-db
    restart: always
    build:
      context: ./config/db
      args:
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_USR_PWD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - makina-network
  api:
    container_name: makina-api
    restart: always
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - makina-network

networks:
  makina-network:
